language: java

sudo: true

jdk: oraclejdk8

services:
    - postgresql
    - docker

env:
    global:
        - GIT_NAME="Joerg Bellmann"
        - GIT_EMAIL=joerg.bellmann@googlemail.com
        - CI_DEPLOY_USERNAME=jbellmann
        - APP_VERSION=0.5-$SIGGI_PROJECT_BUILD_NUMBER

before_install:
    - psql -c 'CREATE DATABASE simple_test;' -U postgres
    - git config user.name "$GIT_NAME"
    - git config user.email "$GIT_EMAIL"
    - git config credential.helper "store --file=.git/credentials"
    - echo "https://$GH_TOKEN:@github.com" > .git/credentials

script:
    - mvn versions:set -DnewVersion=$APP_VERSION --batch-mode
    - mvn clean install -Pmaven-docker --batch-mode
    - sudo docker login -e $GIT_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
    - sudo docker push sigmalab/spring-boot-docker-example:$APP_VERSION
    - mvn scm:checkin -DpushChanges=false -Dmessage="build-by-siggi" --batch-mode
    - mvn -Dtag="$APP_VERSION" scm:tag --batch-mode

